// <auto-generated />
using System;
using HSPAS.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HSPAS.Api.Migrations
{
    [DbContext(typeof(HspasDbContext))]
    [Migration("20260310144112_ExpandRemarkTo500")]
    partial class ExpandRemarkTo500
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HSPAS.Api.Entities.DailyStockPrice", b =>
                {
                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("date");

                    b.Property<string>("StockId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MarketType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("TSE");

                    b.Property<decimal?>("ClosePrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("HighPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("LowPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("OpenPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("PriceChange")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TradeValue")
                        .HasColumnType("decimal(19,4)");

                    b.Property<long?>("TradeVolume")
                        .HasColumnType("bigint");

                    b.Property<int?>("Transaction")
                        .HasColumnType("int");

                    b.HasKey("TradeDate", "StockId", "MarketType");

                    b.ToTable("DailyStockPrice");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.DcaExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OtherCost")
                        .HasColumnType("decimal(19,4)");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("DcaExecution");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.DcaPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CycleDay")
                        .HasColumnType("int");

                    b.Property<string>("CycleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DcaPlan");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.EtfInfo", b =>
                {
                    b.Property<string>("EtfId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("EtfName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Issuer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EtfId");

                    b.ToTable("EtfInfo");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.LifeElectricityBillPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("AvgPricePerKwh")
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("BillingDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("BillingEndDate")
                        .HasColumnType("date");

                    b.Property<string>("BillingPeriodText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("BillingStartDate")
                        .HasColumnType("date");

                    b.Property<string>("BlackoutGroup")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("InvoiceAmount")
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InvoicePeriod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Kwh")
                        .HasColumnType("int");

                    b.Property<decimal?>("KwhPerDay")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("PowerNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RawDetailJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadOrDebitDate")
                        .HasColumnType("date");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SharedMeterHouseholdCount")
                        .HasColumnType("int");

                    b.Property<string>("TariffType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(19,2)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PowerNo", "BillingEndDate");

                    b.HasIndex("PowerNo", "ReadOrDebitDate");

                    b.ToTable("Life_ElectricityBillPeriod");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.MenuFunction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FuncCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RouteUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncCode")
                        .IsUnique();

                    b.ToTable("MenuFunction");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.QuarterHealthReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("HospitalName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OcrJsonRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("date");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("QuarterHealthReport");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.QuarterHealthReportDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AcSugar")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool?>("AcSugarHigh")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CKDEPI_EGFR")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("Creatinine")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("HDL")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool?>("HDLLow")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Hba1c")
                        .HasColumnType("decimal(4,2)");

                    b.Property<bool?>("Hba1cHigh")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MDRD_EGFR")
                        .HasColumnType("decimal(6,2)");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SGPT_ALT")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("TCholesterol")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Triglyceride")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool?>("TriglycerideHigh")
                        .HasColumnType("bit");

                    b.Property<decimal?>("UricAcid")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("QuarterHealthReportDetail");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.TradeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OtherCost")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("TradeRecord");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.DcaExecution", b =>
                {
                    b.HasOne("HSPAS.Api.Entities.DcaPlan", "Plan")
                        .WithMany("Executions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.QuarterHealthReportDetail", b =>
                {
                    b.HasOne("HSPAS.Api.Entities.QuarterHealthReport", "Report")
                        .WithOne("Detail")
                        .HasForeignKey("HSPAS.Api.Entities.QuarterHealthReportDetail", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.DcaPlan", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("HSPAS.Api.Entities.QuarterHealthReport", b =>
                {
                    b.Navigation("Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
